package model;

/**
 * Strong Entities, whose primary key is managed and created by the DB
 */
public abstract class AutoGeneratedIdentity<T> extends DomainObject<T>{
    protected static final long defaultKey = -1;

    public AutoGeneratedIdentity(T identityKey, long version) {
        super(identityKey, version);
    }

    protected abstract void newdentityKey(T key);

    public static long getDefaultKey() {
        return defaultKey;
    }

    public void setIdentityKey(T key){
        if(identityKey.equals(defaultKey))
            newdentityKey(key);
    }
}
