package model;

/**
 * Strong Entities, whose primary key is managed and created by the DB
 */
public abstract class AutoGeneratedIdentity extends DomainObject<Long>{
    protected static final long defaultKey = -1;

    public AutoGeneratedIdentity(Long identityKey, long version) {
        super(identityKey, version);
    }

    public static long getDefaultKey() {
        return defaultKey;
    }

    public void setIdentityKey(long key){
        if(identityKey == defaultKey)
            identityKey = key;
    }
}
