package model;

import util.Streamable;

import java.util.stream.Stream;

public class Curriculum extends AutoGeneratedIdentity<String>{

    @ID
    private final long accountId;
    @ID
    private final long curriculumId;
    private final String title;

    private final Streamable<PreviousJobs> previousJobs;
    private final Streamable<AcademicBackground> academicBackground;
    private final Streamable<Project> projects;

    private Curriculum(long accountId,
                       long curriculumId,
                       String title,
                       Streamable<PreviousJobs> previousJobs,
                       Streamable<AcademicBackground> academicBackground,
                       Streamable<Project> projects,
                       long version) {
        super(String.format("%d%n-%d%n", accountId, curriculumId), version);
        this.accountId = accountId;
        this.curriculumId = curriculumId;
        this.title = title;
        this.previousJobs =  previousJobs;
        this.academicBackground = academicBackground;
        this.projects = projects;
    }

    public static Curriculum create(long accountId,
                                    String title,
                                    Streamable<PreviousJobs> previousJobs,
                                    Streamable<AcademicBackground> academicBackground,
                                    Streamable<Project> projects,
                                    long version)
    {
        Curriculum curriculum = new Curriculum(accountId, defaultKey, title, previousJobs, academicBackground, projects, version);
        curriculum.markNew();
        return curriculum;
    }

    public static Curriculum load(long accountId,
                                  long curriculumId,
                                  String title,
                                  long version,
                                  Streamable<PreviousJobs> previousJobs,
                                  Streamable<AcademicBackground> academicBackground,
                                  Streamable<Project> projects)
    {
        Curriculum curriculum = new Curriculum(accountId, curriculumId, title, previousJobs, academicBackground, projects, version);
        curriculum.markClean();
        return curriculum;
    }

    public long getAccountId() {
        return accountId;
    }

    public long getCurriculumId() {
        return curriculumId;
    }

    public String getTitle() {
        return title;
    }

    public Stream<PreviousJobs> getPreviousJobs() {
        return previousJobs.get();
    }

    public Stream<AcademicBackground> getAcademicBackground() {
        return academicBackground.get();
    }

    public Stream<Project> getProjects() {
        return projects.get();
    }

    @Override
    protected void newdentityKey(String key) {
        identityKey = String.format("%d%n-%s", accountId, key);
        curriculumId = Long.parseLong(key); //TODO ???
    }
}
