package model;

import dataMapping.utils.UnitOfWork;

public abstract class DomainObject<K> {

    /**
     * The key to find the object on the AutoGeneratedIdentity Map
     */
    protected static final long defaultKey = -1;
    protected final K identityKey;
    protected final long version;

    public DomainObject(K identityKey, long version) {
        this.identityKey = identityKey;
        this.version = version;
    }

    public K getIdentityKey() {
        return identityKey;
    }

    public long getVersion() {
        return version;
    }

    public long getNextVersion() {
        return version + 1;
    }

    /**
     * Always called when creating new object
     */
    protected void markNew() {
        UnitOfWork.getCurrent().registerNew(this);
    }

    /**
     * Always called when reading an object from DB
     */
    protected void markClean() {
        UnitOfWork.getCurrent().registerClean(this);
    }

    /**
     * To be always called before making any changes to the object and calling markDirty()
     */
    protected void markToBeDirty(){
        UnitOfWork.getCurrent().registerClone(this);
    }

    /**
     * Always called when altering an object
     */
    protected void markDirty() {
        UnitOfWork.getCurrent().registerDirty(this);
    }

    /**
     * Always called when removing an object
     */
    protected void markRemoved() {
        UnitOfWork.getCurrent().registerRemoved(this);
    }
}
