package model;

public class JobExperience extends AutoGeneratedIdentity{
    private final long jobExperienceId;
    private final long jobId;
    private final long version;

    public JobExperience(long jobExperienceId,long jobId, long version){
        super(jobExperienceId,version);
        this.jobExperienceId = jobExperienceId;
        this.jobId = jobId;
        this.version = version;
    }

    public static JobExperience create(long jobId, long version) {
        JobExperience jobExperience = new JobExperience(defaultKey,jobId,version);
        jobExperience.markNew();
        return jobExperience;
    }

    public static JobExperience load(long jobExperienceId,long jobId, long version) {
        JobExperience jobExperience = new JobExperience(jobExperienceId,jobId,version);
        jobExperience.markClean();
        return jobExperience;
    }


    public long getJobExperienceId() {
        return jobExperienceId;
    }

    public long getJobId() {
        return jobId;
    }

    @Override
    public long getVersion() {
        return version;
    }
}
